config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root  'posts#index' 
  resources :posts do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
    member do
      get 'search'
    end
  end
  resources :users, only: [:show]
  
  # get 'posts' => 'posts#index'
  # get 'posts/new'  =>  'posts#new' 
  # post  'posts'      =>  'posts#create' 
  # get   'users/:id'   =>  'users#show'
  # get   'pots/:id/edit'  => 'posts#edit'
  # patch   'posts/:id'  => 'posts#update'
  # delete  'posts/:id'  => 'posts#destroy'
  # get 'posts/:id' => 'posts#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments 
  has_many :likes, dependent: :destroy  #主キーテーブル（post）が消えるときは、外部キーテーブル(like)も消えるように設定
  has_many :liked_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  
  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(text: params[:text], post_id: params[:post_id], user_id: current_user.id)
    redirect_to "/posts/#{@comment.post.id}" 
  end
  
  private
  def comment_params
    params.permit(:text, :post_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])

    @like = Like.new(
      post_id: params[:post_id],
      user_id: current_user.id
    )

    if @like.save
      redirect_to post_path(@post)
    else
      render template: 'posts/show'
    end
  end
  
  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_to post_path(params[:post_id])
  end

  private
    def like_params
      params.require(:like).permit(:post_id, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :move_to_index, except:  [:index, :show]
  
  def index
    @posts = Post.includes(:user).order("created_at DESC").page(params[:page]).per(5)
    
  end
  
  def new
  end
  
  def create
    Post.create(title: posts_params[:title], text: posts_params[:text], user_id: current_user.id)
  end
  
  def destroy
    post = Post.find(params[:id])
    if post.user_id == current_user.id
      post.destroy
    end
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.includes(:user)
    @like = Like.new()
  end
  
  def update
    post = Post.find(params[:id])
    if post.user_id == current_user.id
      post.update(posts_params)
    end
  end
  
  def search
    @posts = Post.where('text LIKE(?)', "%#{params[:keyword]}%").limit(20).order("created_at DESC").page(params[:page]).per(5)
    @keyword = params[:keyword]
  end
  
  private
  def posts_params
    params.permit(:title, :text)
  end
  
  def move_to_index
  redirect_to action: :index unless user_signed_in?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    
    # 各ユーザーのマイページ
    user = User.find(params[:id])
    @nickname = user.nickname
    @posts = user.posts.page(params[:page]).per(5).order("created_at DESC")

    # どのマイページ見ても自分のが打つ売る
    @nickname = current_user.nickname
    @posts = current_user.posts.page(params[:page]).per(5).order("created_at DESC")
    # @posts = Post.where(user_id: current_user.id)
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Miniblog2</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    

  </head>

  <body>
    <div><%= image_tag 'section_image.jpg',class: 'section' %></div>
    <div class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">Blog</a></h1>
        <div style="display: none;" id="grid-6">
        <% if user_signed_in? %>
          <ul>
            <a href="/users/<%= current_user.id %>">マイページ</a>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
            <li><a class="post" href="/posts/new">投稿する</a></li>
          </ul>
        <% else %>
          <ul>
            <li><%= link_to 'ログイン', new_user_session_path %></li>
            <li><%= link_to '新規登録', new_user_registration_path %></li>
          </ul>
        <% end %>
        </div>
        <!--JSの機能をつけてみるよ※勉強してから-->
        <div id="toggle">
          <div class="one"></div>
          <div class="two"></div>
          <div class="three"></div>
        </div>

      </div>
    </header>


    <%= yield %>

    <div class= "footer">
      Copyright © yazawa All Rights Reserved.
    </div>

  </body>
</html>

app/views/posts/_post.html.erb
        <div class= "main-contents">
          <div class= "title"><%= post.title %></div>
            <div class= "article">
              <div class= "text">
              <%= simple_format(post.text) %>
              </div>
            <span class="name">
              <a href="/users/<%= post.user.id %>">
              投稿者名：<%= post.user.nickname %></span>
              </a>
            </div>
            <div class= "menu">
              <ul>
                <% if user_signed_in? && current_user.id == post.user_id %>
                <li><%= link_to 'destory', "/posts/#{post.id}", method: :delete %></li>
                <li><%= link_to 'edit', "/posts/#{post.id}/edit", method: :get %></li>
                <% end %>
                <li><%= link_to 'show', "/posts/#{post.id}", method: :get %></li>
              </ul>
            </div>
        </div>

app/views/posts/create.html.erb
<div class="contents row">
  <div class= "post-result">
  <h3>投稿できたよ</h3>
  <a class="btn" href="/posts">投稿一覧へ戻る</a>
  </div>
</div>

app/views/posts/destroy.html.erb
<div class="contents row">
  <div class= "post-result">
  <h3>削除完了です</h3>
  <a class="btn" href="/posts">投稿一覧へ戻る</a>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="contents row">
  <div class= "form-contents">
    <%= form_tag("/posts/#{@post.id}", method: :patch) do %>
      <h3>
        編集する
      </h3>
      <p><textarea type="text" name="title" placeholder="title" cols="53"><%= @post.title %></textarea></p>
      <p><textarea name="text" placeholder="text" rows="10" cols="53"><%= @post.text %></textarea></p>
      <p><div class="submit"><input type="submit" value="SEND"></div></p>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
    <div class= "contents row">
      <% if user_signed_in? %>
        <div class="search-section">
          <div class="header_section">
            <h6>投稿を探す</h6>
          </div><h5>
              <form action="/posts/<%= current_user.id %>/search" accept-charset="UTF-8" method="get">
                <input name="utf8" type="hidden" value="✓">
                <input class="search__query" name="keyword" placeholder="キーワードで検索" type="text" value="">
                <button class="btn-search" title="検索" type="submit"><i class="icon-search">検索</i></button>
              </form>
              </h5>
        </div>
      <% end %>
      <% @posts.each do |post| %>
        <%= render partial: "post", locals: { post: post } %>
      <% end %>
      <%= paginate(@posts) %>
    </div>

app/views/posts/new.html.erb
<div class="contents row">
  <div class= "form-contents">
    <%= form_tag('/posts', method: :post) do %>
      <h3>
        投稿する
      </h3>
      <p><textarea type="text" name="title" placeholder="title" cols="53"></textarea></p>
      <p><textarea name="text" placeholder="text" rows="10" cols="53"></textarea></p>
      <p><div class="submit"><input type="submit" value="SEND"></div></p>
    <% end %>
  </div>
</div>

app/views/posts/search.html.erb
    <div class= "contents row">
        <div class="search-section">
          <div class="header_section">
            <h6>結果結果</h6>
            <h6>キーワード"<%= @keyword %>"</h6>
          </div>
        </div>

      <% @posts.each do |post| %>
        <%= render partial: "post", locals: { post: post } %>
      <% end %>
    <%= paginate(@posts) %>
    </div>

app/views/posts/show.html.erb
    <div class= "contents row">
        <div class= "main-contents">
          <div class= "title">タイトル：<%= @post.title %></div>
            <div class= "article">
              <div class= "text">
              <%= simple_format(@post.text) %>
              </div>
            <span class="name">
              <a href="/users/<%= @post.user.id %>">
              投稿者名：<%= @post.user.nickname %></span>
              </a>
              <a class="good-amount">いいね件数: <%= @post.likes.count %></a>

              <!--イイね機能-->
              <button class="good-btn">
              <% if current_user.already_liked?(@post) %>
                <%= button_to 'いいねを取り消す', post_like_path(@post), method: :delete %>
              <% else %>
                <%= form_for [@post, @like] do |f| %>
                  <% if @like.errors.any? %>
                    <% @like.errors.full_messages.each do |msg| %>
                      <li style="color: red;"><%= msg %></li>
                    <% end %>
                  <% end %>
                  <%= f.submit 'いいね！' %>
                <% end %>
              <% end %>
              </button>

            </div>
            <div class= "menu">
              <ul>
                <% if user_signed_in? && current_user.id == @post.user_id %>
                <li><%= link_to 'destory', "/posts/#{@post.id}", method: :delete %></li>
                <li><%= link_to 'edit', "/posts/#{@post.id}/edit", method: :get %></li>
                <% end %>
              </ul>
            </div>
        </div>
        
      <h4>＜この記事にいいねしたユーザー＞</h4>
      <% @post.liked_users.each do |user| %>
        <li><%= user.nickname %></li>
      <% end %>

      <div class="container"> 
        <!-- ここからフォーム -->
        <% if current_user %>
          <%= form_tag("/posts/#{@post.id}/comments", method: :post) do %>
            <p><textarea name="text" placeholder="コメントする" rows="2" cols="54"></textarea></p>
            <input type="submit" value="sent">
          <% end %>
        <% end %>
      </div>
        
            <!-- ここから追記してください -->
        <div class="comments">   
          <h4>＜コメント一覧＞</h4>
          <% if @comments %>
            <% @comments.each do |comment| %>
              <p>
                <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
                <%= comment.text %>
              </p>
            <% end %>
          <% end %>
        </div>
    </div>

app/views/posts/update.html.erb
<div class="contents row">
  <div class= "post-result">
  <h3>更新できたよ</h3>
  <a class="btn" href="/posts">投稿一覧へ戻る</a>
  </div>
</div>

app/views/users/show.html.erb
    <div class= "contents row">
      <p><%= @nickname %>さんの投稿一覧</p>
      <% @posts.each do |post| %>
        <div class= "main-contents">
          <div class= "title">タイトル：<%= post.title %></div>
            <div class= "article">
              <div class= "text">
              <%= simple_format(post.text) %>
              </div>
            </div>
            <div class= "menu">
              <ul>
                <% if user_signed_in? && current_user.id == post.user_id %>
                <li><%= link_to 'destory', "/posts/#{post.id}", method: :delete %></li>
                <li><%= link_to 'edit', "/pots/#{post.id}/edit", method: :get %></li>
                <% end %>
                <li><%= link_to 'show', "/posts/#{post.id}", method: :get %></li>
              </ul>
            </div>
        </div>
      <% end %>
      <%= paginate(@posts) %>
    </div>